apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-ettersending
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 8000
  liveness:
    path: /isAlive
    initialDelay: 5
  readiness:
    path: /isReady
    initialDelay: 5
  prometheus:
    enabled: true
    path: /metrics
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  env:
    - name: APP_VERSION
      value: "{{version}}"
    {{#each env}}
    - name: {{@key}}
      value: "{{this}}"
    {{/each}}