apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: familie-ef-ettersending
  namespace: teamfamilie
  labels:
    team: teamfamilie
spec:
  image: {{ image }}
  team: teamfamilie
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  port: 9000
  liveness:
    path: /internal/isAlive
    initialDelay: 5
  readiness:
    path: /internal/isReady
    initialDelay: 5
  ingresses:
    - "https://ensligmorellerfar.dev.nav.no/familie/alene-med-barn/ettersending"
  accessPolicy:
    outbound:
      external:
        - host: dekoratoren.dev.nav.no
  resources:
    limits:
      cpu: 2000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  env:
    - name: APP_VERSION
      value: "{{version}}"
    - name: ENV
      value: dev
    - name: BASE_PATH
      value: "{{base_path}}"