name: Build, push, and deploy app to prod

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

permissions:
  id-token: write
  contents: read

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: yarn
          registry-url: 'https://npm.pkg.github.com'
      - name: Yarn install
        run: yarn --prefer-offline --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}
      - name: Yarn build
        run: yarn build
      - name: Push docker image to GAR and sign image
        uses: nais/docker-build-push@v0
        id: docker-build-push
        with:
          team: teamfamilie
          identity_provider: ${{ secrets.NAIS_WORKLOAD_IDENTITY_PROVIDER }}
          project_id: ${{ vars.NAIS_MANAGEMENT_PROJECT_ID }}
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
  deploy:
    name: Deploy to gcp
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy til dev-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .deploy/nais-dev.yaml
          IMAGE: ${{ needs.build.outputs.image }}
      - name: Deploy til prod-gcp
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: .deploy/nais-prod.yaml
          IMAGE: ${{ needs.build.outputs.image }}
