name: Build, push, and deploy app to dev

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
env:
  IMAGE: ghcr.io/navikt/familie-ef-ettersending:${{ github.sha }}

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and pubilsh Docker image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.READER_TOKEN }}
        run: |
          docker build -t ${IMAGE} . --build-arg NPM_TOKEN=${NPM_TOKEN} 
          echo ${GITHUB_TOKEN} | docker login ghcr.io --username ${GITHUB_REPOSITORY} --password-stdin
          docker push ${IMAGE}
  deoploy:
    name: Deploy to NAIS
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: build_n_deploy/naiserator/nais-dev.yaml

